name: Auto Commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ubuntu:devel"
    
    steps:
      - name: Trust My Directory
        # run: git config --global --add safe.directory /__w/github-action-playground/github-action-playground
        run: |
          apt-get update
          apt-get install -y git
          export GIT_CEILING_DIRECTORIES=/__w # don't work
      - uses: actions/checkout@v3

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body: test?
          tag_name: v0.0.1
          files: README.md
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}