name: Auto commit

on:
  push:
    branches:
      - master
    workflow_dispatch:
  
  schedule:
    - cron: "0 7,8,9,10,11 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    container: "ubuntu:devel"

    steps:

      - name: Trust My Directory
        # run: git config --global --add safe.directory /__w/go-green/go-green
        run: |
          apt-get update
          apt-get install -y git
          export GIT_CEILING_DIRECTORIES=/__w # don't work

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
        
      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
      - name: Commit changes
        run: |
          git config --local user.email "akulahalannugraha@gmail.com"
          git config --local user.name "yaelahlan"
          git add -A
          arr[0]="feat: 😎 [Go-Green] Feeling good"
          arr[1]="feat: 🌳 [Go-Green] Plant Trees"
          arr[2]="feat: 🌷 [Go-Green] Planting Flowers"
          arr[3]="feat: 🌾 [Go-Green] Planting Rice"
          arr[4]="feat: 🌻 [Go-Green] Planting Sunflowers"
          arr[5]="feat: 🍀 [Go-Green] Planting Green Leaves"
          arr[6]="feat: 🌞 [Go-Green] Photosynthesize"
          arr[7]="feat: 💰 [Go-Green] Take The Harvest"
          arr[8]="feat: 🍀 [Go-Green] Github Go Green"
          arr[9]="feat: 🛍 [Go-Green] Say No To Plastic Bags"

          rand=$[$RANDOM % ${#arr[@]}]
          git commit -m "${arr[$rand]}"
     - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body: test?
          tag_name: v0.0.1
          files: README.md
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}